
package xx.mx.uv.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "comprasPort", targetNamespace = "https://t4is.uv.mx/compras")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComprasPort {


    /**
     * 
     * @param agregarProductoAlCarritoRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.AgregarProductoAlCarritoResponse
     */
    @WebMethod(operationName = "AgregarProductoAlCarrito")
    @WebResult(name = "AgregarProductoAlCarritoResponse", targetNamespace = "t4is.uv.mx/compras", partName = "AgregarProductoAlCarritoResponse")
    public AgregarProductoAlCarritoResponse agregarProductoAlCarrito(
        @WebParam(name = "AgregarProductoAlCarritoRequest", targetNamespace = "t4is.uv.mx/compras", partName = "AgregarProductoAlCarritoRequest")
        AgregarProductoAlCarritoRequest agregarProductoAlCarritoRequest);

    /**
     * 
     * @param seguimientoCompraRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.SeguimientoCompraResponse
     */
    @WebMethod(operationName = "SeguimientoCompra")
    @WebResult(name = "SeguimientoCompraResponse", targetNamespace = "t4is.uv.mx/compras", partName = "SeguimientoCompraResponse")
    public SeguimientoCompraResponse seguimientoCompra(
        @WebParam(name = "SeguimientoCompraRequest", targetNamespace = "t4is.uv.mx/compras", partName = "SeguimientoCompraRequest")
        SeguimientoCompraRequest seguimientoCompraRequest);

    /**
     * 
     * @param generarOrdenCompraRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.GenerarOrdenCompraResponse
     */
    @WebMethod(operationName = "GenerarOrdenCompra")
    @WebResult(name = "GenerarOrdenCompraResponse", targetNamespace = "t4is.uv.mx/compras", partName = "GenerarOrdenCompraResponse")
    public GenerarOrdenCompraResponse generarOrdenCompra(
        @WebParam(name = "GenerarOrdenCompraRequest", targetNamespace = "t4is.uv.mx/compras", partName = "GenerarOrdenCompraRequest")
        GenerarOrdenCompraRequest generarOrdenCompraRequest);

}
